# permissions for end users to view functions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: firebase-controller
    app.kubernetes.io/managed-by: kustomize
  name: function-viewer-role
rules:
- apiGroups:
  - firebase.timam.dev
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - firebase.timam.dev
  resources:
  - functions/status
  verbs:
  - get
