apiVersion: firebase.timam.dev/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: firebase-controller
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  Runtime: nodejs18
  source:
    container:
      image: ghcr.io/timam/firebase-function-sample:latest
      imagePullPolicy: Always
  project:
    auth:
      serviceAccountKey:
        secretName: firebase-credentials
        mountPath: /var/secrets/google

